### ISSUE TITLE
Scanner interrupt error

### ISSUE THREAD

**Issue by wo4zhuzi** [ontio/ontology-explorer#292]
Cannot continue when running to 1293992 blocks

error message:

```
her to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[ INFO ] [2020-09-28 11:04:33] com.github.ontio.asyncService.BlockHandleService [79] - handleOneBlock run-------blockHeight:1293992,txnSum:1
[ INFO ] [2020-09-28 11:04:33] com.github.ontio.thread.TxnHandlerThread [69] - TxnHandlerThread--1 run--------blockHeight:1293992
[ INFO ] [2020-09-28 11:04:33] com.github.ontio.thread.TxnHandlerThread [82] - ####txnType:208, txnHash:72008c3be6a9347a4b315905e090ed5c0c68fe3ecdfa98c7bfde3245d5f75377####
[ INFO ] [2020-09-28 11:04:33] com.github.ontio.thread.TxnHandlerThread [88] - eventObj:{"GasConsumed":10800000000,"Notify":[{"States":["transfer","AGPEo841BiE7G5BoQFQS3AvVBnfg47PdRR","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10800000000],"ContractAddress":"0200000000000000000000000000000000000000"}],"TxHash":"72008c3be6a9347a4b315905e090ed5c0c68fe3ecdfa98c7bfde3245d5f75377","State":1}
[ ERROR] [2020-09-28 11:04:34] com.github.ontio.thread.TxnHandlerThread [172] - handleOneTxn RestfulException...{}
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at com.github.ontio.network.rest.RestClient.getContractJson(RestClient.java:191)
        at com.github.ontio.sdk.manager.ConnectMgr.getContractJson(ConnectMgr.java:235)
        at com.github.ontio.thread.TxnHandlerThread.getSmartContractInfo(TxnHandlerThread.java:746)
        at com.github.ontio.thread.TxnHandlerThread.handleOneTxn(TxnHandlerThread.java:99)
        at com.github.ontio.thread.TxnHandlerThread.asyncHandleTxn(TxnHandlerThread.java:71)
        at com.github.ontio.thread.TxnHandlerThread$$FastClassBySpringCGLIB$$67ea581d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at com.github.ontio.network.rest.RestClient.getContractJson(RestClient.java:191)
        at com.github.ontio.sdk.manager.ConnectMgr.getContractJson(ConnectMgr.java:235)
        at com.github.ontio.thread.TxnHandlerThread.getSmartContractInfo(TxnHandlerThread.java:746)
        at com.github.ontio.thread.TxnHandlerThread.handleOneTxn(TxnHandlerThread.java:99)
        at com.github.ontio.thread.TxnHandlerThread.asyncHandleTxn(TxnHandlerThread.java:71)
        at com.github.ontio.thread.TxnHandlerThread$$FastClassBySpringCGLIB$$67ea581d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
[ ERROR] [2020-09-28 11:04:34] com.github.ontio.asyncService.BlockHandleService [98] - error...session.rollback
java.util.concurrent.ExecutionException: com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.github.ontio.asyncService.BlockHandleService.handleOneBlock(BlockHandleService.java:90)
        at com.github.ontio.asyncService.BlockHandleService$$FastClassBySpringCGLIB$$cfe8ad64.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
```

From the error message, the getcontract method reported an error. But I tested it with curl, and there was no error in the contract. What did the code do

This is my test result：
![image](https://user-images.githubusercontent.com/20334885/94387187-f3557000-017b-11eb-8351-b98429b6f206.png)

**Comment by wo4zhuzi** [comment]
When I skip this block and can continue to run, is there any special difference between this block and other blocks?

![image](https://user-images.githubusercontent.com/20334885/94388455-ab384c80-017f-11eb-9470-9f15cb0766e0.png)
